#let white = rgb("#fefefc")
#let black = rgb("#1e1e1e")
#let blacker = rgb("#151515")
#let charcoal = rgb("#2f2f2f")
#let faff-pink = rgb("#ffaff3")
#let unnamed-blue = rgb("#a6f0fc")
#let underwater-blue = rgb("#292d3e")
#let unexpected-aubergine = rgb("#584355")
